# Generated by Django 4.1.7 on 2023-02-19 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart', models.TextField()),
                ('price', models.FloatField(max_length=10)),
                ('status', models.CharField(choices=[('SC', 'Success'), ('PD', 'Pending'), ('ER', 'Error'), ('CN', 'Canceled')], default='PD', max_length=20)),
                ('ethAddress', models.CharField(max_length=50)),
                ('hash_num', models.CharField(max_length=100)),
                ('text', models.TextField(max_length=100)),
                ('create_date', models.DateTimeField()),
                ('last_update_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ammount', models.FloatField()),
                ('date', models.DateTimeField()),
                ('order_id', models.PositiveIntegerField()),
            ],
        ),
    ]
