# Generated by Django 4.1.7 on 2023-03-08 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0002_alter_orders_create_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Returns',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ammount', models.FloatField()),
                ('date', models.DateTimeField()),
                ('order_id', models.IntegerField()),
                ('hash', models.TextField()),
            ],
        ),
    ]
