# Generated by Django 4.1.7 on 2023-02-19 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categories', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('text', models.TextField()),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart', models.TextField()),
                ('price', models.FloatField(max_length=10)),
                ('ethAddress', models.CharField(max_length=50)),
                ('hash_num', models.CharField(max_length=100)),
                ('text', models.TextField(max_length=100)),
                ('create_date', models.DateTimeField()),
                ('last_update_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='payments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ammount', models.FloatField()),
                ('date', models.DateTimeField()),
                ('order_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.TextField(max_length=180)),
                ('name', models.TextField(max_length=90)),
                ('rating', models.IntegerField(max_length=2)),
                ('slug', models.TextField(max_length=200)),
                ('category', models.CharField(max_length=20)),
            ],
        ),
    ]
