# Generated by Django 4.1.7 on 2023-02-19 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_products_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='status',
            field=models.CharField(choices=[('S', 'Success'), ('P', 'Pending'), ('E', 'Error'), ('C', 'Canceled')], default='P', max_length=1),
        ),
    ]
